---
title: "HW 1"
author: "Colby Reichenbach"
date: "01/26/2024"
output:
  pdf_document: default
  html_document:
    number_sections: true
  word_document: default
---

We have now seen three ethical theories as well as their pitfalls.  We have also thoroughly discussed their applications to the justifibility chat GPT.

# 

Now it is your turn to demonstrate your own understanding and mastery of these philosophical concepts.  To what extent, or under what circumstances, is the use of Chat-GPT justifiable in academic settings?  Use (at least) one of the above principles as a supporting argument for your position.  Argue for your position in one page or less. 

# 

In no more than half a page, consider and refute a potential objection to the position you staked out in the above question. 

\newpage
With the invention of the calculator, the ability of a student to do math without such a tool was brought into question. With time, we learned that the calculator became a tool that would speed up the process of math forever, without inhibiting the growth of learning. The introduction of ChaptGPT brings in similar concerns, transcending a singular subject or field of study. Its capabilities can no doubt be used to undermine academia, but it can also act solely as a supplement to one's learning. In this way ChatGPT becomes not only a justifiable tool, but one of the best tools in all of technology.

#

As students progress through school, courses become more intense and difficult to follow. Some fall behind as they are stuck trying to comprehend the material or work through problems. ChatGPT then can act as a supplement for those students. Asking ChatGPT to explain the topic in an elementary way lessens the difficult language and makes the topics easier to follow, which could speed up the process of learning the material while maintaining academic integrity. This not only prevents students from falling behind in the subject, but grants them more free time they can use to better their overall well being. This position is well defended by consequentialism, more specifically utilitarianism, because it maximizes the students happiness. It provides an easier way to learn the material, minimizing stress, and maximizes the amount of free time a student has to indulge in hobbies or other things that promote a happy and healthy presence.

#

To further this example, homework, specifically for STEM majors, can consist of hours of strenuous and confusing problems. Math, for example, can have problems that take a whole page to solve. It is easy to mark a number with the wrong sign and arrive at a wrong answer. Though traversing the problem to find the error is a clear cut way to fix it, it can take a very long time to find the error, or you might not be able to find it at all. Students who have multiple classes with this structure might find that there is a lack of time to go through these problem sets and do each and every problem the right way, especially if a student also has other responsibilities such as work and caring for others. Then, is it justifiable to ask ChatGPT to help solve the problem and help it identify your mistake? It is important to note that asking ChatGPT will provide a framework with steps for the problem, and not simply give an answer. Therefore, this allows pinpointing of the error, allowing the student to recognize the error made and keep note of it while working on other problems.In this case, deontology would deem these actions justifiable because the intentions of the student are to get a better understanding of the material and get better at solving the following problems in an efficient way. 

#

Though these are two examples of ways ChatGPT may be justifiable in the eyes of deontology and utilitarianism, they could be argued against. If the intention was using the tool to supplement the learning, but it instead hindered the full understanding of the material, and provided a lesser understanding that was accompanied with a false confidence in their ability to comprehend and reproduce it, then would it still be justifiable? Consequentialism would say no, because the consequences hurt the student more than helped. However, this fails to recognize that the student still has a duty to understand the limitations of AI. In this case ChatGPT carried out its duty to supplement the student learning, the student now has a duty to use this supplemented 
learning to further their understanding of the concept to make sure that they understand it as a whole and not just have an understanding of the supplemented parts provided by ChatGPT.

#

In all, ChatGPT and other AI is a justifiable tool in aiding students in their studies as long as the student upholds their duty to use it as a supplement and not as a replacement.